### ISSUE TITLE
Incompatibel with latest Microsoft-IME for Japanese

### ISSUE THREAD

**Issue by stonerl** [SafeExamBrowser/seb-win#115]
**Describe the Bug**
In mid 2020, Microsoft introduced a new input method for Japanese, with which SEB is not compatible. Allowing **Show keyboard layout** in the SEB-settings does not display the Japanese Input Method in SEB for the users. The only way to type Japanese is, to enable the previous Microsoft-IME for Japanese.

**Steps to Reproduce**
1. Go to the Windows Settings.
2. Add Japanese (all features but don't set it as default language)
3. Select Japanese form the language list and make sure that Microsoft-IME is added under the keyboard section.
4. Start SEB with **Show keyboard layout** allowed. In the keyboard list, only the native keyboard (in my case German) is available but not Japanese.

**Expected Behavior**
SEB should show the Japanese input for the old and new Microsoft-IME

**Version Information**
 - OS: Edition	[Windows 10 Pro - 20H2 - build 19042.746]
 - SEB-Version [SEB 3.1.1_250]

**Comment by dbuechel** [comment]
The IME only works with kiosk mode "Disable Explorer Shell", not with the default mode "Create New Desktop".

**Comment by stonerl** [comment]
So, is this a bug or a feature?

**Comment by danschlet** [comment]
The problem is that Microsoft is not doing anything to allow assessment/kiosk browsers to lock down the system directly, using some Windows API, especially when using BYOD (student owned computers) and not PCs managed by the university/school. We have to use various tricks to achieve a secure mode with SEB. Other operating system vendors like Apple in iOS and recently also macOS provide system APIs for secure assessment modes even when using BYOD. 

Maybe it helps if you file a feature request to Microsoft about that.

**Comment by stonerl** [comment]
Thank you for the clarification.
