### ISSUE TITLE
Changing window with 'Windows + array' keys => stuck in fullscreen SEB taskbar

### ISSUE THREAD

**Issue by jp-weber** [SafeExamBrowser/seb-win#18]
### Description

If I minimalized the screen with 'Windows + down' keys and maximized the screen with the “Windows + up” keys, the browser is stuck in fullscreen SEB taskbar.

### Environment & Version
- [x] Windows

OS-Version: 10.15063(.540) \
SEB-Version: 2.1(.6)

### Steps to Reproduce

1. focus a window with the mouse
2. press 'Windows + Down' key
3. press 'Windows + Up' key

**Comment by dbuechel** [comment]
Hi there

Thanks for your issue report. I was indeed able to reproduce the problem with SEB 2.1.5 as well as 2.1.6. In my case, however, it minimized the browser window and then maximized the SEB taskbar, I did not see a white screen.

Unfortunately, we will not be able to fix the issue before the release of SEB 2.2. I checked whether the problem does pertain to the current build of 2.2, and that appears not to be the case. If it is an urgent matter, I recommend you to use the current pre-release of SEB 2.2. Otherwise, you could wait for the official release of SEB 2.2 somewhen later this year.

Cheers,
Damian

**Comment by revan1199** [comment]
Hi, thanks for the fast respond :-)

no problem that the issue is not fix until SEB 2.2 is released. 

"maximized the SEB taskbar"
Yes this is correct, my mistake with the white screen.
