### ISSUE TITLE
Adding a certificate in the config tool doesn't work

### ISSUE THREAD

**Issue by ShooterMcGee** [SafeExamBrowser/seb-win#27]
# Adding a P12 certificate doesn't work

### Description

When I import a certificate file into Safe Exam Browser, it doesn't do anything. Am I doing something incorrectly or are .p12 files unsuitable for this function? Any help greatly appreciated.

I don't know if this is the right place to post this, if not, please notify me.

### Environment & Version

Acer Aspire V15, decent specs

- [ ] Mac
- [x] Windows

OS-Version: Windows 10: 1709
SEB-Version: Latest

### Steps to Reproduce

1. import .p12 file
2. navigate to site where the .p12 file is needed
3. Still get an "ACCESS DENIED 403"

**Comment by dbuechel** [comment]
Did you do it according to the manual, and e.g. set the private key as "exportable"? See [https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPaneCertificatesSection](https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPaneCertificatesSection)

**Comment by danschlet** [comment]
The question is also what kind of certificates do you want to use? SSL/TLS server certificates usually wouldn't be distributed as a .p12 package file, because you don't need a private key to connect to the server, only the certificate containing the public key of the secure server. Usually the .cer format is used for those certificates. Just double click a .cer file and let Windows install it into the default certificate store for that type of certificate, then you can select it in SEB Config Tool / Network / Certificates and embed it in a config file (see attached screenshots). But SEB 2.1.x only accepts perfectly valid certificates, for example the server's URL has to be contained in the certificate (as "common name" or in "alternative names"). In SEB 2.2 (see preview testing version) you can add a "debug" certificate, there validity and trust is not checked. 

If you intend to use client certificates (for authenticating to a server supporting this), that's currently not supported in SEB. It could somehow work with SEB 2.2, as the used [seb2 browser engine ](https://github.com/eqsoft/seb2)supports client certificates, but there is currently no direct support in the SEB client.

SEB supports certificates in the .p12 format for encrypting and decrypting SEB config files, but I guess that's not what you are looking for.

**Comment by ShooterMcGee** [comment]
The weird thing is that i got it working for a bit, then I deleted everything regarding the certificate. It didnt work outside of SEB, but inside SEB the certificate worked normally... Now I'm not able to reproduce that. And yes, I did follow the manual but that didnt work.

Kind Regards,
McGee
