### ISSUE TITLE
SEB and idlelogoff.exe

### ISSUE THREAD

**Issue by trombonekenny** [SafeExamBrowser/seb-win#40]
### Description

Our instructional labs use the [IntelliAdmin Idle Logoff tool](http://www.intelliadmin.com/?p=4439) enforced through GPO at login to automatically logoff sessions that are idle for 30 minutes. We observed students getting automatically logged out 30 minutes after starting their SEB session even though they were actively using the computers.

Does something about the way SEB secures the system obscure the keystroke or mouse tracker that determines if the system is idle?

### Environment & Version

- [ ] Mac
- [x] Windows

OS-Version: Windows 7 Pro systems (did not test with Win10, but that's coming soon for us)
SEB-Version: 2.2

### Steps to Reproduce

Start the idlelogoff.exe with a timeframe and logout functionality. Then fire up SEB and interact inside of it. (In our recent scenario, SEB allowed Excel access as well. It's possible the students spent all of that idle time limit in Excel and NOT interacting with SEB.)

**Comment by dbuechel** [comment]
SEB does indeed intercept the mouse and keyboard input on a low level. However, since the typing of normal characters itself has to work in order to answer questions, I don't think they are the problem. It might however be that the kiosk mode is causing this problem: If you are using Create New Desktop, SEB will run on a new desktop and the logoff tool might not be able to recognize that (i.e. nothing is happening on the standard desktop during SEB's runtime). You could verify that by switching to kiosk mode Disable Explorer Shell.

**Comment by danschlet** [comment]
SEB usually prevents the Windows idle timer (or however it is called) to start a screen saver, switch off a display or let the computer sleep. It's strange that this tool doesn't respect the system wide idle timer, seems to me like the tool isn't implemented correctly. Maybe you'll find a better tool for this functionality.

In case screen savers or automatic idle sleep does kick in on your computers even when SEB is running, then we would need to investigate if this SEB feature maybe doesn't work on some systems.

**Comment by danschlet** [comment]
Closed as no additional feedback was delivered.
