### ISSUE TITLE
[Feature request] - make it possible to block new browser windows and/or block resizing the main SEB windows

### ISSUE THREAD

**Issue by stemiwe** [SafeExamBrowser/seb-win#43]
[Feature request] - make it possible to block new browser windows and/or block resizing the main SEB windows

### Description

Right now it is possible to open links that open in a new browser window and/or open resources in Moodle that open in a popup windows.

Combined, both of these can lead to problems, since students can potentially open resources from a Moodle course in a new window, and then use [Windows] + [Arrow Key] Shortcuts to show/hide that additional window next to SEB.

### Environment & Version

- [ ] Mac
- [x] Windows

OS-Version: Win10
SEB-Version: 2.2

### Steps to Reproduce

1. Create a file resource for a PDF in Moodle that opens as a Popup
2. Create a Moodle Quiz that uses SEB in the same course
3. Before starting the Quiz, open the file resource in SEB - it will open in a Popup in front of the main SEB browser window
4. Click on the main SEB browser window to hide the resource. Use [Windows] + [Arrow Left] to resize the SEB window to the left half of the screen to view the resource again, and [Windows] + [Arrow Right] to hide it again

**Comment by webers-technikum-wien** [comment]
quick workaround for others having the same issue: there is a handy little program that disables the windows key, kalled winkill.exe.

you can just autostart this one via SEB and it will not be possible any more to move the SEB window around

**Comment by webers-technikum-wien** [comment]
While I agree that there should be a secure landing page, this would not change our problem, since we use one default configuration for our clients, so the users log into moodle via the normal start page anyways.

What we did is have a local user account on our machines that starts SEB as a shell instead of explorer upon login - that alone solves a lot of problems, but it also makes it impractical to use multiple configurations. (We still offer the possibility of custom configurations to our teachers, for example to allow additional programs, but it is rarely used. Those custom configurations are then started from the normal user account).

I'm actually quite happy with the workaround with WinKill that I found, because the SEB window has no controls for resize, so if you disable the Windows Key you cannot resize it any more, and also cannot show / hide a potential second window, so this way of cheating becomes impractical.

**Comment by danschlet** [comment]
Unfortunately there's also a Firefox key shortcut Alt+Space. I'll let our browser developer investigate if he block that (but I don't think it was possible when we looked at that some years ago). I guess we should prioritize the option to not open additional browser windows.

**Comment by danschlet** [comment]
Btw., didn't you realize that Alt+Tab and the SEB-Icon in the SEB taskbar can be used to switch between all open browser windows? 

We don't have this problem with out Moodle exams because we use a separate exam instance of Moodle, where user accounts are synchronized, but students don't have access to their Moodle profile with any kind of resources which they might place there beforehand. 

Thanks anyways for pointing out this issue, we didn't get this reported before. We will try to find a solution in SEB.

**Comment by webers-technikum-wien** [comment]
sorry for the late reply - semester start....

i cant really replicate how to use alt-tab or the SEB-icon - once SEB is started, it shouldnt be possible to have more than one browser window open, right? and alt-tab can be disabled in the "hooked keys" tab in SEB config, and that seems to work nicely

so the only real issue is popups, since popups in moodle courses still open. those windows, however, cant be switched with alt-tab and dont show up in the SEB bar, so the only options to show/hide them is to resize or minimize the main SEB window

unfortunately, alt+space does pretty much the same as windows + arrow keys, but my guess is less people know about it, so we ll be happy for this semester having disabled the more popular cheating option... i don't think you can do anything about alt+space from a browser point of view, since its a windows hotkey. however, maybe there is a way to make the SEB main window non-resizable and non-minimizable? im pretty sure i saw other applications do that

the other doable option would be to disable popups - since there are already browser extension that do just that, that should be possible as well

**Comment by danschlet** [comment]
SEB 3.0 allows to block opening additional browser windows.
