### ISSUE TITLE
Password in command line options for safe exam browser?

### ISSUE THREAD

**Issue by nicowitteman** [SafeExamBrowser/seb-win#50]
# Password in command line options for safe exam browser?

### 
We would like to use a specific SEB configuration file to install certificates on all computers in a certain location in order to restrict the possibility of decrypting an exam configuration file later. For this, the option "Use SEB settings file for ... configuring a client" combined with "Network/security/certificates/choose identity to embed into configuration" appears appropriate. But we would like to protect this first configuration file with a password. And we would like to be able to run Safe exam browser with this configuration from a script. 
Is there a way we can pass the password to the application with the configuration file name?

### Environment & Version
PC 

- [ ] Mac
- [x] Windows

OS-Version: 10
SEB-Version: 2.2.1

**Comment by danschlet** [comment]
Currently it's not possible to pass a settings password to the application together with the configuration file name, but that's a good suggestion which we will keep in mind for a future update.

On managed computers you currently could deploy the certificates using a deployment system onto the computers. Or you use an unencrypted client config file, but don't copy it onto the computers, you could open it from a shared drive and delete it after the clients are configured, as SEB won't copy the embedded certificate from the config file to the AppData\Roaming\SafeExamBrowser\ directory. The certificate is saved in the Windows Certificate Store and removed from the client config which is saved persistently in the mentioned directory.

**Comment by nicowitteman** [comment]
Another question related to the embedded certificate: it appears these are imported into the certificate store of the current user. I think it would be better to import them into the "local machine" store, in order to make them available for any user who logs in to the computer.

**Comment by danschlet** [comment]
I should maybe explain this further:

- The reason why the identity certificates (X.509 certificate including a private key) are stored in the Windows Certificate Store or the macOS Keychain is, that the operating system protects that private key relatively well
- The client config file is by default encrypted, but only with a standard encryption key. If you don't encrypt it with a password (or theoretically you could also use another identity certificate) and leave this original client config file on the exam computers, the embedded certificate is still inside there and is less well protected than in the Certificate Store.
- So if you distribute client config files on managed computers (usually you should place the SebClientConfig.seb named file in the \ProgramData\SafeExamBrowser\ directory then, so it's accessible to all users), you should make sure they don't contain the embedded certificate because the above point.
- This is why you need to use a deployment system to place the identity certificate in the Local Machine/Trusted People store. Then it will be accessible to all users on that machine.

In the case of BYOD, if SEB is started by opening the client config file (or better a sebs:// link to it), then SEB starts and copies all settings besides the embedded identity certificates to the SebClientSettings.seb file in the user's AppData directory. The identity certificates are only stored in the Certificate Store.

Hope this makes it a bit clearer.

**Comment by nicowitteman** [comment]
Thanks, Daniel.
