### ISSUE TITLE
Chrome browser showed as white window

### ISSUE THREAD

**Issue by dudul** [SafeExamBrowser/seb-win#52]
### Description

When the user open the chrome browser (Chrome exe is allowed) it showed as a window without UI (white window)
It seems that it's starting to happen from Chrome version 70.
Chrome version 69.0.3497.92 works fine.

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [x] Windows
- [ ] Mac

OS-Version: 10
SEB-Version: 2.2.2
Chrome Version: 70.0.3538.77 (64-bit)

### Steps to Reproduce
1. Create a configuration file, add the "Chrome" exe to "Permitted Processes" and save it.
2. Run the SafeExamBrowser with this configuration file.
3. Press the chrome icon on the task bar.
4. Chrome opened as a white blank window.

![2018-10-28_181544](https://user-images.githubusercontent.com/4558838/47618568-8479c300-dadd-11e8-8e5b-7c2679ba9ab0.png)

**Comment by danschlet** [comment]
Looks like Google messed up in Chrome 70. It might have to do with the "Create new desktop" kiosk mode with SEB uses by default, earlier we had similar issues with some plugins like Flash, because they were running in a separate process which didn't start up on the new desktop SEB creates.

To verify that's the issue you can try to change the kiosk mode to "Disable Explorer Shell" or "None" for testing (Security tab in SEB Config Tool). In general we don't recommend using "Disable Explorer Shell" with BYOD though (SEB can't prevent that some apps can display notifications in this mode). If Chrome 70 only doesn't work when using Create new desktop, then there might not be any other solution. Try to file a bug report to Google.

Why are you using Chrome at all during an exam? That's not really a use case for us. Why not use the SEB browser to display additional web sites (if that's what you're doing)?

**Comment by dudul** [comment]
I used chrome just to check the SEB.
I hope it will not happen on another process

**Comment by danschlet** [comment]
Well, it's possible that some software won't work as third party application together with SEB. Nevertheless when using the "Disable Explorer Shell" mode, we run all kinds of complex applications without problems (inside of virtual desktops, as complex applications make only sense to be run inside of managed machines).

UWP apps in general don't work as third party applications. Microsoft would need to support that in the Windows API.
