### ISSUE TITLE
Sticky Keys problem

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-win#59]
Pressing the shift key five times is a shortcut for "Sticky keys". In SEB, this brings up a dialog window, which is closed immediately. However, using a really well timed mouse press (and some luck), the "help link" in this dialog may be pressed, which opens the system settings (in explorer), with possible access to files/information on the device.

It's really hard to get the timing right, but I seem to manage in perhaps one out of 30 tries. An exam supervisor would probably detect this, but it may be the case that the timing is different (easier) on other hardware.

In high volume exams, this may also eventually occur by mistake.

### Environment & Version

- [ ] Mac
- [x] Windows 10

SEB-Version: 2.2.2

### Steps to Reproduce

1. Start SEB with lockdown enabled.
2. Press shift 5 times, which opens and immediately closes the dialog window.
3. Try to press the information link with the mouse.
4. Repeat until success. It may be "impossible" on some hardware, and easier on some. On my computer, it's hard but possible.

I'm proposing to not show this dialog at all, or at least behind the browser window.

**Comment by danschlet** [comment]
Are you sure you're using SEB 2.2.2 (and not 2.2) and you don't have the kiosk mode switched off Security / Kiosk Mode - None (for debugging only) ? 

Send us the SebClient.log file and indicate which date/time you tried it.

I tried it in both kiosk modes (default Create new desktop and Disable Explorer Shell) and despite succeeding to press the link, the system Settings panel never was displayed. In Create new desktop it is displayed behind the new desktop SEB is running on, you can see it when you quit SEB. In Disable Explorer Shell since I think 2.2.1 Explorer.exe is terminated automatically in the case it starts up during the exam.

Which Windows version are you using, 1803 (or the new 1809)? I tried it with 1803.

**Comment by Krisell** [comment]
I'm sorry about not getting back to you on this yet. I currently don't have access to the computer I used previously, and I can't seem to trigger this cheat on my current computer (which is newer). I will try again next week, check the windows version and send the log file.

I'm sure I did not have the kiosk-mode switched off, and I'm also sure I used at least SEB 2.2.1, but I will double check and see if I can reproduce it.

**Comment by Krisell** [comment]
I have now been able to reproduce this issue on Windows 1709.

Also, after this issue has occured, SEB does not close properly when using the quit-button or quit-link. It just shows a black window. I restarted the computer to solve this. This happened every time I reproduced the Sticky-keys-issue.

Here's the SebClient.log, and I stripped out the old entries.
[SebClient.log](https://github.com/SafeExamBrowser/seb-win/files/2652978/SebClient.log)

Here are three images. 
The first one shows the window that pops up after successfully clicking the help-link in the Sticky-Keys window. I managed to go from there to "This computer" (image 2). The third image shows a strange behavior when clicking the "Abort"-button, and I noticed similar effects on other elements. It seems like the individual elements, rather than the whole window, is being hidden.

![img_7687](https://user-images.githubusercontent.com/25909128/49583148-8b56e980-f957-11e8-94fb-424e626cd83f.JPG)
![img_3289](https://user-images.githubusercontent.com/25909128/49583146-8b56e980-f957-11e8-936b-9b7e7de13db9.JPG)
![img_3226](https://user-images.githubusercontent.com/25909128/49583147-8b56e980-f957-11e8-9c94-2261c4580dfb.JPG)

**Comment by Krisell** [comment]
The process that is lauched by activating the sticky-keys function by pressing shift five times is Windows\System32\sethc.exe By replacing this file with the contents of explorer.exe, pressing shift five times now **immediately opens explorer**. It is still "hard" to navigate, but using the keyboard and pressing windows+arrow-down simplifies this by minimizing the browser.

The issue remains in 2.2.3. Do you have any suggestions of how to handle this currently? I tried to add sethc.exe to the list of prohibited processes with no luck.

@danschlet

**Comment by dbuechel** [comment]
Thanks a lot for your detailed report. I didn't have a chance yet to check the detailed information you sent us via mail, but I shall do so first thing next week.

**Comment by dbuechel** [comment]
I was able to reproduce the starting of `explorer.exe` instead of `sethc.exe`, and it is true, for some reason the new explorer window is not hidden immediately (though it is only really usable via keyboard, as you already described). However, I fail to understand how this could allow cheating: As soon as you try to open a document or alike, the new window (be it e.g. Word or the Editor) is immediately hidden, as is the open explorer window...

**Comment by Krisell** [comment]
Thank you for investigating this. I'm not sure you received my additional information via email? I send it to info@safeexambrowser.org.
