### ISSUE TITLE
Students can switch user with CTRL + ALT + DELETE

### ISSUE THREAD

**Issue by danielx** [SafeExamBrowser/seb-win#65]
# Students can switch user with CTRL + ALT + DELETE

### Description

We've gotten reports from one customer that their students can access the switch user screen by pressing CTRL + ALT + DELETE in SEB.

### Environment & Version

Windows 10 for Education

- [ ] Mac
- [x] Windows

OS-Version: X.X(.X) \
SEB-Version: 2.2

### Steps to Reproduce

This only seems to affect that customers computers AFAIK.

1. Press CTRL + ALT + DELETE
2. Change user
3. Google answers
4. Change back to previous user and SafeExamBrowser
5. Continue exam

## Question

My main question is how we can find the root cause why this customers students can consistently access the switch user screen even though it should be blocked.

I've noticed that the option to enable user switching is in the registry section of the SEB Config tool.
Am i correct in assuming that SEB won't be able to block the user from the switch user screen using CTRL + ALT + DELETE if the user running SEB can't make registry changes? Or does SEB block the switch screen CTRL + ALT + DELETE functionality in a way that should not require any privileges/registry modifications at all?

Since they are using Windows with Swedish language they can't try version 2.2.2 due to issue #53 

EDIT: i've asked them to try with 2.2.3pre2 aswell

**Comment by dbuechel** [comment]
Ensure that the correct service policy is set in the configuration ("allow to use SEB only with service"): [https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane](https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane).

If it still doesn't work, check the log files mentioned in the link above to see whether they contain any further information...

**Comment by danschlet** [comment]
SEB 2.2.3 for Windows should be released in the next couple of weeks, the next iOS update had higher priority. You can use 2.2.3 also in Sweden, you just would need to ignore the error message and calculate two Browser Exam Keys for Windows set to Swedish and to other languages.

The issue you're observing was most likely fixed in SEB 2.2.1, but there was another issue with the Browser Exam Key in that version, so if you're using the BEK, then it's probably better to use 2.2.2 with the limitation mentioned above or wait for 2.2.3.
