### ISSUE TITLE
4K displays and 150% scaling

### ISSUE THREAD

**Issue by ndum** [SafeExamBrowser/seb-win#70]
Hello,

We have a problem with SEB 2.2.3 (2.2.2 doesn't work either) with 4K displays and 150% scaling. Mouse clicks in SEB don't work then. I looked through the issues and saw that this had happened before. [12](https://github.com/SafeExamBrowser/seb-win/issues/12)

Is there any other solution than reducing the scaling to 100%? (100% reducing is working, but this is not really a solution...)

Thank you.

**Comment by dbuechel** [comment]
You'll need to at least sign out of your account after changing the scaling factor (though I recommend a complete restart). The issue should be fixed, but since it only occurred with kiosk mode "Create New Desktop", you could try "Disable Explorer Shell" for an immediate workaround in case the problem has truly reappeared.

**Comment by ndum** [comment]
"Disable Explorer Shell" has solved the problem Thanks! although I don't quite understand why ;)
