### ISSUE TITLE
Unable to start Demo-test exam

### ISSUE THREAD

**Issue by jorjoh** [SafeExamBrowser/seb-win#8]
Hi, as of version 2.1.3 I'm currently unable to start the demo-exam in safe exam browser.
I always get the message here displayed in the picture below:
![seb](https://cloud.githubusercontent.com/assets/8746948/22429718/d0ad7a04-e70b-11e6-820f-d0a619864be9.PNG)

Current windows version 10 Pro
Application installed with admin privileges 

Regards
Jørgen Johansen
Student At UiA Norway

**Comment by danschlet** [comment]
Please contact your exam provider or the responsive IT support people at your university. It seems that they are providing the wrong type of SEB configuration, which configures the permanent settings of the SEB application installed on your computer instead of starting the exam. In general we would need more information to find out if and what kind of issue causes this, in case it is really a bug in SEB (used config file, testing login, SEB log files).

**Comment by jorjoh** [comment]
will do, thank you
