### ISSUE TITLE
Suppress dialog 

### ISSUE THREAD

**Issue by pajda777** [SafeExamBrowser/seb-win#9]
Hello,
would it be possible to add parameter to a configuration file to suppress this dialog in the future version:

"New settings have been saved, they will be used when you start SEB next time again. Do you want to start working with SEB or quit for now?"

Thanks a lot !

Pavel Sanca

**Comment by danschlet** [comment]
Hi,
Please describe your scenario and why you want to suppress this dialog. This dialog is displayed when the user opens a config file which reconfigures the persisted settings of the client. In this case it is best practice to give feedback to the user that this happened and succeeded. Also they should be able to quit SEB if they don't want to start working with it at the time of initially configuring it (as quitting might be restricted in those settings).

If you want to deploy settings to exam clients unattended or directly start an exam then read the manuals about how this is done.

**Comment by pajda777** [comment]
Hello,

what we do is:  the SEB config file is dynamically created for particular exam and user, then we send it to the client and the  SEB starts with that file (user sees that dialog).

We haven't found a way how to start any exam for any user dynamically.

Thanks!

**Comment by danschlet** [comment]
Hi Pavel,

When creating the SEB config file, you should use the same format as if a config file is saved in the SEB Config Tool with the option "Use SEB settings file for ... starting an exam". [See manual](http://safeexambrowser.org/windows/win_usermanual_en.html#ConfigFilePane): "A configuration file saved with this option will start the exam with the according settings, but won't change local SEB settings."

If you implemented dynamically creating the SEB config file, you have to use another prefix (pswd instead of pwcc) inside the config file structure:
pswd	Password, stands for encrypted data using a password. 
plnd	Plain data, stands for unencrypted, gzip compressed data, see below.
pwcc	Password, configuring a client. This kind of .seb file is used for changing the local preferences which are used when the SEB application is started up directly (not by opening a .seb file). In the Mac OS X SEB client settings are written into the file ~/Library/Preferences/org.safeexambrowser.Safe-Exam-Browser.plist. The Windows version writes the settings to the file SebClientSettings.seb in the „AppData“ directory.

As far as I understood your scenario using "for starting an exam" is much better, also because the config file data isn't written onto the local drive of the exam client computer but only kept in RAM during the exam.

I attached the latest (not yet published) version of the config file format specification document. Please not that from SEB 2.2 there will be a new encryption method added for asymetrical/symetrical encryption of config files using X.509 certs/keys. The specification document is work-in-progress, the config keys are not yet updated to the current state of the various SEB versions and branches. I'm planing to put all the specifications on our GitHub-based website, so it will be easier to keep it updated and have centralized documentation.

Which exam system are you using or working on which generates the config files dynamically? We would be happy to know systems for which an integration for SEB exists (we are also planing a list with links on the safeexambrowser.org website, for those companies who are interested in publicly listing their exam products on the SEB website). You can also contact us directly if you prefer this instead of answering here.

[Specification_SEB_Configuration_v17.pdf](https://github.com/SafeExamBrowser/seb-win/files/864432/Specification_SEB_Configuration_v17.pdf)

**Comment by pajda777** [comment]
Hello,

I passed this info you provided to my developer...thanks!

We are company called WebStudy and we provide LMS with the same name. (See WebStudy.com)
The SEB integration is on production servers over a year and so far it is much better experience than Respondus LDB for our users.

Thanks again for your efforts!

 Pavel Sanca
