### ISSUE TITLE
SEB Failed to completely lockdown the computer

### ISSUE THREAD

**Issue by EmreGltkn** [SafeExamBrowser/seb-win#95]
Whenever I open the program it says "Failed to completely lockdown the computer" I have exams someone please help me!

**Comment by dbuechel** [comment]
Are you using any VMware or anti-virus products?

**Comment by uqswalk5** [comment]
I am running remote exams with students in China and many encounter this problem. I saw a post some weeks back saying that this was a known bug in 2.4 and would be fixed in 2.4.1 but I have not seen a release of that version. I have been advising students to uninstall 2.4 and install 2.3 which has worked for some but not all.

**Comment by uqswalk5** [comment]
https://github.com/SafeExamBrowser/seb-win/issues/91

**Comment by uqswalk5** [comment]
Hi Damien, can you confirm if 2.4.1 containing the fix referred to in #91 has been released?

**Comment by dbuechel** [comment]
No, this version is still in testing at the moment

**Comment by danschlet** [comment]
[SEB 2.4.1](https://safeexambrowser.org/download_en.html#WindowsLegacy) which should fix this issue was now released.
